/// Audio asset paths, relative to `assets/audio/` (flame_audio's default
/// prefix). The shipped files are silent placeholders generated by
/// `tool/generate_placeholder_audio.dart` — drop in real sound to enable audio
/// (see SETUP.md). Music + SFX (docs/CONCEPT.md §audio, ANALYTICS sfx events).
abstract final class AudioAssets {
  static const String musicAmbient = 'music/ambient_loop.wav';

  static const String sfxLaunch = 'sfx/launch.wav';
  static const String sfxBounce = 'sfx/bounce.wav';
  static const String sfxStar = 'sfx/star.wav';
  static const String sfxWin = 'sfx/win.wav';
  static const String sfxLose = 'sfx/lose.wav';

  /// All SFX clips, preloaded on init.
  static const List<String> sfx = [
    sfxLaunch,
    sfxBounce,
    sfxStar,
    sfxWin,
    sfxLose,
  ];
}
